#!/usr/bin.exec-suid -- /usr/bin/python3 -I

import flask
import os
app = flask.Flask(__name__)

@app.route("/docking_station", methods=["GET"])
def a():
    return

@app.route("/secret_meeting", methods=["GET"])
def b(path = "index.html"):
    for i in range(len(path)):

    requested_path = app.root_path + "/tables/" + path[::-1]