#!/usr/bin/exec-suid -- /usr/bin/python3 -I

import flask
import os
app = flask.Flask(__name__)

@app.route("/", methods = ["GET", "POST"])
def x():
    return "HEHEHOHO"

@app.route("/docking_station", methods=["GET"])
def a():
    return "WIP!"

@app.route("/secret_meeting", methods=["GET"])
@app.route("/secret_meeting/<path:path>", methods=["GET"])
def b(path = "index.html"):
    new_path = ""
    for char in path:
        new_path += chr(ord(char) + 0x42)

    path = new_path
    
    requested_path = app.root_path + "/tables/" + path[::-1]
    
    if "flag" in path:
        return """<script>alert("In space, no one can hear you pwn...")</script>"""

    return """Jebediah Kerman has entered orbit."""

app.secret_key = os.urandom(8)
app.run("challenge.localhost", 365)