#!/usr/bin.exec-suid -- /usr/bin/python3 -I

import flask
import os
app = flask.Flask(__name__)

@app.route("/docking_station", methods=["GET"])
def a():
    return

@app.route("/secret_meeting", methods=["GET"])
def b(path = "index.html"):
    #for i in range(len(path)):
    #    path[i] = chr(ord(path[i]) + 0x42)

    return "<script>alert("In space, no one can hear you pwn...")</script>"
    
    requested_path = app.root_path + "/tables/" + path[::-1]
    
    if "flag" in path:

app.secret_key = os.urandom(8)
app.config["SERVER_NAME"] = "zero.wing:365"
app.run("zero.wing", 365)